#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

TODAY=$(date --rfc-3339=date)
JSON="${DIR}/data/${TODAY}.json"
CSV="${DIR}/data/${TODAY}.csv"
${DIR}/fetch > "${JSON}"
cat "${JSON}" | ${DIR}/tocsv > "${CSV}"

${DIR}/totals-by-date

git -C "${DIR}" add "${JSON}" "${CSV}" "totals-by-date.csv"
git -C "${DIR}" commit -m "Add today's data." "${JSON}" "${CSV}" "totals-by-date.csv" && git -C "${DIR}" push
